name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: gradlew check
      run: |
        ./gradlew check
    - run: ./gradlew runDebugExecutableNative